title: quieres ser un MEJOR FOTOGRAFO ? este es tu lugar
logo: /images/logo.png
#PWA parameters
pwa: rayando con luz
slogan: Nunca dejemos de opturar!
short_name: rcl
brand_color: white
main_collection: posts
icons: 
  - src: images/launcher-icon-1x.png
    size: 48x48
  - src: images/launcher-icon-2x.png
    size: 96x96
  - src: images/launcher-icon-4x.png
    size: 192x192
#SEO parameters
description: Solo un fotografo mas con ganas de compartir vivencias, concejos y experiencias que puedan aportar a la comunidad fotografica.  todos mis consejos son experiencias propias que me han ayudado a mejorar mi tecnica. espero poder aportar en tu crecimiento.
lang: es
fb_app_id: 1880022215651426
url: https://rayandoconluz.photo # the base hostname & protocol for your site, e.g. http://example.com
email: rutasdelosandes@gmail.com
fbpage: https://www.facebook.com/rayandoconluz/
googlemaps_key: AIzaSyAz1r9qDIaA7lGoMdW7VPpvic7JXZjCdls
google_analytics: UA-100391485-3
instant_pages: 1078600055607267
permalink: /:categories/:title
# Social
twitter: rayandoconluz
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - chatbot
  - server.js
include:
  - node_modules/workbox-sw/build/importScripts/workbox-sw.prod.v1.3.0.js

collections:
  camisetas:
    output: true
    layout: product
    permalink: /:collection/:name
  gorras:
    output: true
    layout: product
    permalink: /:collection/:name


